# Generated by Django 2.0.3 on 2018-03-26 08:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaisDeportado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilesDeUsuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('referencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_Paterno', models.CharField(max_length=40)),
                ('apellido_Materno', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.DateField(default='')),
                ('escolaridad', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('fecha_ultima_deportacion', models.DateField(blank=True, default='', null=True)),
                ('ciudad_actual', models.CharField(max_length=100)),
                ('fecha_llegada', models.DateField(default='', max_length=40)),
                ('solo_acomp', models.CharField(default='', max_length=40)),
                ('familia_ciudad', models.CharField(default='', max_length=40)),
                ('com_familia', models.CharField(default='', max_length=40)),
                ('fam_OCiudad', models.CharField(default='', max_length=40)),
                ('com_Ofamilia', models.CharField(default='', max_length=40)),
                ('ciudad_permanente', models.CharField(default='', max_length=40)),
                ('asiste_agrupacion', models.CharField(default='', max_length=40)),
                ('salir_origen', models.CharField(default='', max_length=40)),
                ('interes_CESFOM', models.CharField(default='', max_length=40)),
                ('estado_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual', to='Migrantes.Estado')),
                ('estado_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Migrantes.Estado')),
                ('pais_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_actual', to='Migrantes.Pais')),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Migrantes.Pais')),
                ('pais_ultima_deportacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Migrantes.PaisDeportado')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Migrantes.Pais'),
        ),
    ]
