# Generated by Django 2.0.4 on 2018-06-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migrantes', '0002_perfilesdeusuario_terminos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilesdeusuario',
            name='tipo_usuario',
            field=models.CharField(default='', max_length=10),
        ),
    ]
