# Generated by Django 2.0.4 on 2018-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migrantes', '0004_auto_20180612_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilesdeusuario',
            old_name='tipo_usuario',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='tipo_usuario',
            name='tipo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
