# Generated by Django 2.0.3 on 2018-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migrantes', '0001_initial'),
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='course',
            name='estudiantes_max',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='course',
            name='estudiante',
            field=models.ManyToManyField(to='Migrantes.PerfilesDeUsuario'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
