# Generated by Django 2.0.3 on 2018-04-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_auto_20180412_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='estudiante',
        ),
    ]
