# Generated by Django 2.0.3 on 2018-04-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_remove_course_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='descripcion',
            field=models.CharField(default='', max_length=250),
        ),
    ]
