# Generated by Django 2.0.3 on 2018-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_course_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
