# Generated by Django 2.0.3 on 2018-04-13 20:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0006_auto_20180412_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=''),
        ),
    ]
