# Generated by Django 2.0.3 on 2018-04-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0010_clases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='clases',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='clases',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='clases',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='clases',
            name='unidad',
        ),
        migrations.DeleteModel(
            name='Clases',
        ),
    ]
