# Generated by Django 2.0.3 on 2018-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0011_auto_20180416_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
    ]
