# Generated by Django 2.0.3 on 2018-04-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Migrantes', '0001_initial'),
        ('Cursos', '0012_auto_20180416_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='estudiante',
            field=models.ManyToManyField(blank=True, to='Migrantes.PerfilesDeUsuario'),
        ),
    ]
