# Generated by Django 2.0.3 on 2018-04-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0014_anuncios_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncios',
            name='curso',
        ),
    ]
