# Generated by Django 2.0.3 on 2018-04-23 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0017_anuncios_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.Course'),
        ),
    ]
