# Generated by Django 2.0.3 on 2018-04-23 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0018_auto_20180422_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='estudiante',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
