# Generated by Django 2.0.4 on 2018-04-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0020_auto_20180427_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Cursos.Course'),
        ),
    ]
