# Generated by Django 2.0.4 on 2018-04-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0021_preguntas_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidotema',
            name='texto',
            field=models.TextField(default='', max_length=500),
        ),
    ]
