# Generated by Django 2.0.4 on 2018-04-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0022_contenidotema_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='respuesta',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
