# Generated by Django 2.0.4 on 2018-04-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0024_auto_20180428_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='respuesta',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
